apiVersion: apps/v1
kind: Deployment
metadata:
  name: searx
  
spec:

  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: searx
  template:
    metadata:
      labels:
        app: searx
    spec:
      containers:
      - name: searx
        image: registry.cloud.okteto.net/roiterorh/searx:latest

        imagePullPolicy: Always


        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: searx
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ports:
    - protocol: TCP
      port: 8080
  selector:
    app: searx
